# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jqvReleK0uKaS5CCfH46IjvlVGMVdatw
"""

from keras.preprocessing import image
from keras.applications import vgg19

#load pre-trained model------------------------
model = vgg19.VGG19()
#----------------------------------------------

img = image.load_img('clock1.jpg', target_size=(224, 224))
img = image.img_to_array(img)
img = img.reshape((1,img.shape[0],img.shape[1],img.shape[2]))
	
img = vgg19.preprocess_input(img)

y_predicted = model.predict(img)
vgg19.decode_predictions(y_predicted)

model.summary()

keras.utils.plot_model(model,to_file='vggnetmodel.png')

vgg19.vgg19.imagenet_utils.CLASS_INDEX